### ISSUE TITLE
Hide 'classroom content' from non-logged in users.

### ISSUE THREAD

**Issue by iandouglas** [stellakunzang/brownfield-of-dreams#7]
Currently all tutorials are visible to anyone. We want to make tutorials marked as "classroom content" viewable only if the user is logged in.

The tutorials table has a boolean column for `classroom` that should be used for this story.

**Comment by perryr16** [comment]
I have hidden tutorials on `'/'` with `classroom: true` from visitors. But a visitor could still type the following URL to see a classroom video (unlikely, but possible) `/tutorials/3` assuming tutorial 3 is for classroom use only. 
If I were to disable that tutorial than the app will not fail gracefully as we cant call methods like `.title` on the view's `@tutorials` because `@tutorials = nil`

is there a way to hit a 404?

**Comment by iandouglas** [comment]
Maybe look at `current_user` and if that's nil then redirect or throw a 404?
